name: Create Release Branch and Pull Request

on:
  workflow_dispatch: # Триггер для выполнения вручную

jobs:
  create-release-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the current version
        id: get_version
        run: |
          VERSION=$(grep -Po '(?<=version = ").*(?=")' build.gradle.kts)
          echo "::set-output name=version::$VERSION"
        shell: bash
      
      - name: Increment the version
        id: increment_version
        run: |
          CURRENT_VERSION=${{ steps.get_version.outputs.version }}
          NEW_VERSION=$(echo "$CURRENT_VERSION + 0.1" | bc)
          NEW_VERSION=$(printf "%.1f" $NEW_VERSION)
          sed -i "s/version = \"$CURRENT_VERSION\"/version = \"$NEW_VERSION\"/g" build.gradle.kts
          git add build.gradle.kts
          git commit -m "Bump version to $NEW_VERSION"
          echo "::set-output name=new_version::$NEW_VERSION"
        shell: bash

      - name: Create a new branch
        run: |
          NEW_VERSION=${{ steps.increment_version.outputs.new_version }}
          BRANCH_NAME="release/version-$NEW_VERSION"
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME
          echo "::set-output name=branch_name::$BRANCH_NAME"
        shell: bash

  create-pull-request:
    runs-on: ubuntu-latest
    needs: create-release-branch

    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ needs.create-release-branch.outputs.branch_name }}
          title: "Release ${{ needs.create-release-branch.outputs.branch_name }}"
          body: "Auto-generated pull request for release"
